name: hellohuts_app
description: Hellohuts Application

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  #database and auth
  cloud_firestore: ^1.0.0
  firebase_core: ^1.0.0
  firebase_storage: ^8.0.0


  #auth methods
  firebase_auth: ^1.0.0
  google_sign_in: ^5.0.0
  sign_in_with_apple: ^3.0.0-nullsafety.0
  flutter_facebook_auth: ^3.0.0-nullsafety.1


  #notifications
  firebase_messaging: ^9.0.0



 #local storage
  shared_preferences: ^2.0.3


 
 #http requests
  http: ^0.13.0


  #analytics
  firebase_analytics: ^7.1.1
  firebase_crashlytics: ^1.0.0



  #state management and dependecy injection
  provider: ^5.0.0
  get_it: ^6.0.0
  get: ^4.0.0-nullsafety.2
  



  #user interface
  google_fonts: ^2.0.0
  flutter_screenutil: ^5.0.0-nullsafety.7
  cached_network_image: ^3.0.0-nullsafety
  expandable_text: ^2.0.0-nullsafety.1

  smooth_page_indicator: ^0.3.0-nullsafety.0
  carousel_slider: ^4.0.0-nullsafety.0
  flutter_svg: ^0.21.0-nullsafety.0
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  flutter_statusbarcolor_ns: ^0.3.0-nullsafety


  # ----For videos----
  # video_player: ^0.11.0
  # video_player_platform_interface: ^2.2.0





  #routing
  auto_route: ^0.6.9

  #utilities
  equatable: ^2.0.0
  logger: ^1.0.0-nullsafety.0
  flutter_hooks: ^0.16.0
  freezed: ^0.14.0
  timeago: ^3.0.1
  hooks_riverpod: ^0.13.0
  url_launcher: ^6.0.2
  share: ^2.0.0
  flutter_linkify: ^5.0.0
  flutter_downloader: ^1.6.0-nullsafety.0
  permission_handler: ^6.0.1
  path_provider: ^2.0.1
  animations: ^2.0.0
 
dependency_overrides:
  freezed: ^0.12.7
  freezed_annotation: ^0.12.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: 
  freezed_annotation:
  json_serializable: ^3.5.1 
  build_runner:
  # build_resolvers: 

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - data/
  
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  fonts:
    - family: HelloIcons
      fonts:
        - asset: assets/icons/HelloIcons.ttf
      